services:
  mariadb:
    image: mariadb:10.5
    container_name: movies_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - movies_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: movies_backend
    restart: always
    environment:
      NODE_ENV: production
      API_PORT: ${API_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      TMDB_API_URL: ${TMDB_API_URL}
      TMDB_API_KEY: ${TMDB_API_KEY}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mariadb
    ports:
      - "${API_PORT}:3000"
    networks:
      - movies_network

volumes:
  mariadb_data:

networks:
  movies_network: