FROM node:22

WORKDIR /app

COPY package*.json ./

RUN npm install -g @ionic/cli && npm install

COPY . .

EXPOSE 8100

# Default command to run Ionic in development mode
CMD ["ionic", "serve", "--host=0.0.0.0", "--port=8100", "--disableHostCheck"]
